### ISSUE TITLE
How can i create a ProvablyFair object?

### ISSUE THREAD

**Issue by omgnobody121** [LucaPuddu/php-provably-fair#12]
How can i create a ProvablyFair object?

**Comment by lucapuddu** [comment]
Hi @tewni-svg,
You can use the `Builder` class like so:
```
$algorithm = 'sha256';
$serverSeed = 'server seed';
$clientSeed = 'client seed';
$nonce = '1';
$min = 23.75;
$max = 44;
$generator = Builder::make()
                    ->algorithm($algorithm)
                    ->serverSeed($serverSeed)
                    ->clientSeed($clientSeed)
                    ->nonce($nonce)
                    ->min($min)
                    ->max($max)
                    ->build();
```

Once you have the generator (a `ProvablyFair` instance), you can start rolling numbers:
```
$number = $generator->roll();

// Change nonce to generate a different number
$nonce = ((int) $nonce) + 1;
// Nonce should be a string, so we pass it in quotes
$generator->setNonce("$newNonce");

$anotherNumber = $generator->roll();
```
This is a low-level library. In a typical scenario you would want to save the _client seed_, _server seed_, _hashed server seed_, _nonce_ and _algorithm_ to your database. This way, you can have the user verify their own rolls.

**Comment by omgnobody121** [comment]
hello, i mean, how i can i import ProvablyFair object

**Comment by lucapuddu** [comment]
1. `composer require lucapuddu/php-provably-fair` in your `package.json`
2. `use LucaPuddu\PhpProvablyFair\ProvablyFair` in your php file. Or `use LucaPuddu\PhpProvablyFair\Builder` if you want to use the `Builder` class as I showed you in the previous message
